Repository bigbite/wp-cypress, pull requests merged in 2021-12, with the labels that each got.

#80 Sync v1 branch with v0.9.2 changes
  lib/utils/watchDir.js
  package.json
  yarn.lock
Labels: chore

#78 Add php memory limit to config
  lib/modules/createConfig.js
  lib/schemas/config-validation.json
  lib/templates/dockerfile.ejs
Labels: enhancement, 1.0.0

#82 Add Windows Support
  lib/cli/commands/reset.js
  lib/cypress-support/commands.js
  lib/modules/exec.js
Labels: 1.0.0
